# Class 0: NOT SAVE - Recall queries (asking for stored info)

RECALL_EXAMPLES = [
    # Direct recall questions
    "What's my name?",
    "What is my name?",
    "What's my name again?",
    "Do you remember my name?",
    "Do you recall my name?",
    "Can you remember my name?",
    "What did I tell you my name was?",
    "Who am I?",
    "What's my email?",
    "What's my email address?",
    "Do you know my email?",
    "What email did I give you?",
    "What's my phone number?",
    "Do you have my phone number?",
    "What number did I give you?",
    "When is my birthday?",
    "What's my birthday?",
    "Do you remember my birthday?",
    "When's my anniversary?",
    "What's my wife's name?",
    "What's my husband's name?",
    "Who is my spouse?",
    "Where do I live?",
    "What city am I in?",
    "Where am I from?",
    "What do I do for work?",
    "Where do I work?",
    "What's my job?",
    "What's my favorite color?",
    "What food do I like?",
    "Do you remember what I told you?",
    "What do you know about me?",
    "What have I shared with you?",
    "Can you recall my preferences?",
    "What allergies do I have?",
    "Am I allergic to anything?",
    "What car do I drive?",
    "Do I have any pets?",
    "What are my kids' names?",
    "How many children do I have?",
    "What timezone am I in?",
    "What pronouns do I use?",
    "What languages do I speak?",
    
    # Variations with different phrasing
    "Remind me what my name is",
    "Tell me my email again",
    "What was my phone number?",
    "I forgot, what's my birthday?",
    "Help me remember my address",
    "What info do you have on me?",
    "Recall my details please",
]
