# Class 1: SAVE REQUESTS - User providing information to store

SAVE_EXAMPLES = [
    # Explicit save/remember commands
    "Remember my name is Sarah",
    "My name is John",
    "I'm called Mike",
    "Can you save that my birthday is May 3rd",
    "Please remember I live in Seattle",
    "Don't forget my email is john@example.com",
    "Keep in mind I prefer vegetarian options",
    "Note that I work at Microsoft",
    "Remember my phone number is 555-1234",
    "Save the fact that I have two cats",
    "My wife's name is Emma",
    "Store this: my favorite color is blue",
    "Remember I'm allergic to peanuts",
    "I speak Spanish fluently",
    "My anniversary is June 15",
    "I drive a Tesla Model 3",
    "My doctor's appointment is at 3pm",
    "I'm training for a marathon",
    "My son goes to Lincoln Elementary",
    "I need to call the bank tomorrow",
    "I have a meeting with Sarah next Monday",
    
    # Casual info sharing (still save-worthy)
    "Just so you know, my name's Sarah",
    "FYI my email is test@example.com",
    "By the way, I'm vegetarian",
    "Oh, I should mention I have a nut allergy",
    "I'm Ian, nice to meet you",
    "The name's Bond, James Bond",
    "Call me Dave",
    "I go by Alex",
    "People call me Professor",
    "I'm from New York originally",
    "I moved to Boston last year",
    "I work in finance",
    "I'm a software engineer",
    "I have three kids",
    "My dog's name is Max",
    "I'm married to Lisa",
    "My favorite food is sushi",
    "I prefer coffee over tea",
    "I'm lactose intolerant",
    "I was born in 1990",
    "My address is 123 Main Street",
    "I prefer morning meetings",
    "I use he/him pronouns",
    "My timezone is PST",
    "I speak French and German",
    
    # Implicit save contexts
    "Here's my contact info: 555-0123",
    "You can reach me at mike@email.com",
    "My schedule is usually free on Fridays",
    "I typically wake up at 6am",
    "I'm available after 2pm",
    "I take my coffee black",
    "I don't eat meat",
    "I'm gluten-free",
    "I have diabetes",
    "I take medication in the morning",
    
    # Document sharing - storing reference material
    "Here's a document about my IT stack",
    "This document outlines my infrastructure",
    "Please remember this specification",
    "Here's my company's network architecture",
    "Store this configuration for me",
    "Keep this document for future reference",
    "This is my setup guide",
    "Here's the documentation I mentioned",
    "Please save this technical spec",
    "This is my IT infrastructure overview",
    "Here's my cloud stack configuration",
    "This document describes my system setup",
    "Save this reference material",
    "Here's my network topology",
    "This outlines my server configuration",
    "Please remember this architecture diagram",
    "Store this runbook for later",
    "Here's my deployment configuration",
    "This is the project specification",
    "Keep track of this design document",
    "Here's my API documentation",
    "This describes my development environment",
    "Save this operational guide",
    "Here's my security policy document",
    "This is my disaster recovery plan",
    "Please parse this document",
    "Parse and remember this information",
    "Can you store this for reference",
    "Keep this info handy",
    "I want you to remember this document",
]
