# Class 1: SAVE REQUESTS - User providing information to store

SAVE_EXAMPLES = [
    # Explicit save/remember commands
    "Remember my name is Sarah",
    "My name is John",
    "I'm called Mike",
    "Can you save that my birthday is May 3rd",
    "Please remember I live in Seattle",
    "Don't forget my email is john@example.com",
    "Keep in mind I prefer vegetarian options",
    "Note that I work at Microsoft",
    "Remember my phone number is 555-1234",
    "Save the fact that I have two cats",
    "My wife's name is Emma",
    "Store this: my favorite color is blue",
    "Remember I'm allergic to peanuts",
    "I speak Spanish fluently",
    "My anniversary is June 15",
    "I drive a Tesla Model 3",
    "My doctor's appointment is at 3pm",
    "I'm training for a marathon",
    "My son goes to Lincoln Elementary",
    "I need to call the bank tomorrow",
    "I have a meeting with Sarah next Monday",
    
    # === PERSONAL NAME SHARING (CRITICAL - was being misclassified) ===
    "My name is Ian",
    "My name is Bob",
    "My name is Alice",
    "My name is David",
    "My name is Jennifer",
    "My name is Michael",
    "My name is Emily",
    "My name is Chris",
    "My name is Rachel",
    "My name is Tom",
    "My name is Lisa",
    "My name is Kevin",
    "My name is Jessica",
    "My name is Matt",
    "My name is Amanda",
    "I'm Ian",
    "I'm Bob",
    "I'm Alice", 
    "I'm David",
    "I'm Jennifer",
    "I'm Michael",
    "I'm Emily",
    "I'm Chris",
    "I'm Rachel",
    "I'm Tom",
    "Name's Ian",
    "Name's Bob",
    "Name's Sarah",
    "The name is Ian",
    "The name is Sarah",
    "It's Ian",
    "It's Sarah",
    "Ian here",
    "Bob here",
    "Sarah here",
    
    # Casual info sharing (still save-worthy)
    "Just so you know, my name's Sarah",
    "FYI my email is test@example.com",
    "By the way, I'm vegetarian",
    "Oh, I should mention I have a nut allergy",
    "I'm Ian, nice to meet you",
    "The name's Bond, James Bond",
    "Call me Dave",
    "I go by Alex",
    "People call me Professor",
    "I'm from New York originally",
    "I moved to Boston last year",
    "I work in finance",
    "I'm a software engineer",
    "I have three kids",
    "My dog's name is Max",
    "I'm married to Lisa",
    "My favorite food is sushi",
    "I prefer coffee over tea",
    "I'm lactose intolerant",
    "I was born in 1990",
    "My address is 123 Main Street",
    "I prefer morning meetings",
    "I use he/him pronouns",
    "My timezone is PST",
    "I speak French and German",
    
    # === MORE PERSONAL INFO PATTERNS ===
    "I'm 35 years old",
    "I'm 28",
    "I'm in my 40s",
    "My age is 32",
    "Born in 1985",
    "Born on March 5th",
    "My birthday is tomorrow",
    "I was born on Christmas",
    "I turn 30 next month",
    "I'm a Leo",
    "My zodiac sign is Virgo",
    "I'm originally from Texas",
    "I grew up in Chicago",
    "I currently live in Denver",
    "I'm based in London",
    "I relocated to Seattle",
    "I'm staying in New York",
    "My hometown is Portland",
    "I live alone",
    "I live with roommates",
    "I live with my family",
    "I rent an apartment",
    "I own a house",
    "I'm a homeowner",
    
    # === RELATIONSHIP INFO ===
    "I'm married",
    "I'm single",
    "I'm divorced",
    "I'm engaged",
    "I'm in a relationship",
    "My girlfriend's name is Kate",
    "My boyfriend is called Tom",
    "My partner is Sam",
    "My fiancé is moving in",
    "I've been married for 10 years",
    "We have been together 5 years",
    "My ex is named Sarah",
    
    # === WORK/PROFESSION ===
    "I'm a doctor",
    "I'm a teacher",
    "I'm a developer",
    "I'm an engineer",
    "I'm a nurse",
    "I'm a lawyer",
    "I'm a manager",
    "I'm a designer",
    "I'm a consultant",
    "I'm a student",
    "I'm retired",
    "I'm self-employed",
    "I'm a freelancer",
    "I run my own business",
    "I'm the CEO",
    "I'm currently job hunting",
    "I just got promoted",
    "I work remotely",
    "I work from home",
    "I commute to the office",
    "My boss is named Karen",
    "My company is called Acme",
    "I work at Google",
    "I work for Amazon",
    "I work in healthcare",
    "I work in tech",
    "I work in education",
    "My salary is confidential",
    "I make 100k a year",
    
    # === PREFERENCES AND HABITS ===
    "I'm a morning person",
    "I'm a night owl",
    "I wake up at 5am",
    "I go to bed late",
    "I exercise daily",
    "I go to the gym",
    "I run every morning",
    "I do yoga",
    "I meditate",
    "I read before bed",
    "I watch Netflix",
    "I play video games",
    "I collect stamps",
    "My hobby is photography",
    "I enjoy cooking",
    "I love hiking",
    "I hate flying",
    "I'm afraid of heights",
    "I'm claustrophobic",
    
    # Implicit save contexts
    "Here's my contact info: 555-0123",
    "You can reach me at mike@email.com",
    "My schedule is usually free on Fridays",
    "I typically wake up at 6am",
    "I'm available after 2pm",
    "I take my coffee black",
    "I don't eat meat",
    "I'm gluten-free",
    "I have diabetes",
    "I take medication in the morning",
    
    # Document sharing - storing reference material
    "Here's a document about my IT stack",
    "This document outlines my infrastructure",
    "Please remember this specification",
    "Here's my company's network architecture",
    "Store this configuration for me",
    "Keep this document for future reference",
    "This is my setup guide",
    "Here's the documentation I mentioned",
    "Please save this technical spec",
    "This is my IT infrastructure overview",
    "Here's my cloud stack configuration",
    "This document describes my system setup",
    "Save this reference material",
    "Here's my network topology",
    "This outlines my server configuration",
    "Please remember this architecture diagram",
    "Store this runbook for later",
    "Here's my deployment configuration",
    "This is the project specification",
    "Keep track of this design document",
    "Here's my API documentation",
    "This describes my development environment",
    "Save this operational guide",
    "Here's my security policy document",
    "This is my disaster recovery plan",
    "Please parse this document",
    "Parse and remember this information",
    "Can you store this for reference",
    "Keep this info handy",
    "I want you to remember this document",
]
