# Class 0: NOT SAVE - Casual conversation, general questions

CASUAL_EXAMPLES = [
    # Greetings and small talk
    "Hello",
    "Hi there",
    "Hey",
    "Good morning",
    "How are you?",
    "How are you doing?",
    "What's up?",
    "How's it going?",
    "Nice to meet you",
    "Thanks",
    "Thank you",
    "You're welcome",
    "Goodbye",
    "See you later",
    "Take care",
    
    # General questions (not about stored info)
    "What's the weather like?",
    "What time is it?",
    "What day is it?",
    "Can you help me?",
    "What can you do?",
    "Tell me a joke",
    "Tell me a story",
    "What do you think about AI?",
    "How does this work?",
    "What's the capital of France?",
    "Who wrote Romeo and Juliet?",
    "What's 2 plus 2?",
    "Explain quantum physics",
    "Write me a poem",
    "Help me with my code",
    "Debug this function",
    "What's the best programming language?",
    "How do I learn Python?",
    "What's for dinner?",
    "Should I go outside?",
    "Is it going to rain?",
    "What movie should I watch?",
    "Recommend a book",
    "What's trending?",
    "Tell me the news",
    
    # Emotional expressions (not save requests)
    "I'm feeling tired",
    "I'm so happy today",
    "This is frustrating",
    "I'm confused",
    "That's interesting",
    "I don't understand",
    "Can you clarify?",
    "I'm not sure about that",
    "That makes sense",
    "I agree",
    "I disagree",
    "Maybe",
    "I think so",
    "Probably not",
    "Let me think about it",
    
    # Task requests (not save requests)
    "Summarize this article",
    "Translate this to Spanish",
    "Fix this bug",
    "Optimize this code",
    "Write an email",
    "Draft a message",
    "Create a list",
    "Make a table",
    "Calculate this",
    "Analyze this data",
    "Compare these options",
    "Search for restaurants",
    "Find me a flight",
    "Book a hotel",
    "Set a timer",
    "Play some music",
]
