# Class 0: NOT SAVE - Recall queries (asking for stored info)

RECALL_EXAMPLES = [
    # Direct recall questions
    "What's my name?",
    "What is my name?",
    "What's my name again?",
    "Do you remember my name?",
    "Do you recall my name?",
    "Can you remember my name?",
    "What did I tell you my name was?",
    "Who am I?",
    "What's my email?",
    "What's my email address?",
    "Do you know my email?",
    "What email did I give you?",
    "What's my phone number?",
    "Do you have my phone number?",
    "What number did I give you?",
    "When is my birthday?",
    "What's my birthday?",
    "Do you remember my birthday?",
    "When's my anniversary?",
    "What's my wife's name?",
    "What's my husband's name?",
    "Who is my spouse?",
    "Where do I live?",
    "What city am I in?",
    "Where am I from?",
    "What do I do for work?",
    "Where do I work?",
    "What's my job?",
    "What's my favorite color?",
    "What food do I like?",
    "Do you remember what I told you?",
    "What do you know about me?",
    "What have I shared with you?",
    "Can you recall my preferences?",
    "What allergies do I have?",
    "Am I allergic to anything?",
    "What car do I drive?",
    "Do I have any pets?",
    "What are my kids' names?",
    "How many children do I have?",
    "What timezone am I in?",
    "What pronouns do I use?",
    "What languages do I speak?",
    
    # Variations with different phrasing
    "Remind me what my name is",
    "Tell me my email again",
    "What was my phone number?",
    "I forgot, what's my birthday?",
    "Help me remember my address",
    "What info do you have on me?",
    "Recall my details please",
    
    # === MORE RECALL PATTERNS ===
    "What did I say my name was?",
    "You know my name right?",
    "Did I mention my name?",
    "What name did I give?",
    "Remind me who I am",
    "Can you look up my info?",
    "Pull up my details",
    "Check what you know about me",
    "Search your memory for my name",
    "Find my stored information",
    "Retrieve my profile",
    "Access my saved data",
    "Look up my preferences",
    "What preferences have I set?",
    "What did I tell you about myself?",
    "What have you remembered about me?",
    "What's stored about me?",
    "What's in my profile?",
    "Show me my saved info",
    "Display my information",
    "List what you know about me",
    
    # Questions about specific info (all recalls)
    "How old am I?",
    "What's my age?",
    "When was I born?",
    "What year was I born?",
    "What's my address?",
    "Where's my house?",
    "What street do I live on?",
    "What's my zip code?",
    "What country am I from?",
    "What state do I live in?",
    "What's my hometown?",
    "What company do I work for?",
    "Who's my employer?",
    "What's my title?",
    "What's my position?",
    "What's my occupation?",
    "What's my profession?",
    "What's my salary?",
    "How much do I make?",
    "What's my partner's name?",
    "What's my girlfriend's name?",
    "What's my boyfriend's name?",
    "What's my dog's name?",
    "What's my cat's name?",
    "What pet do I have?",
    "What's my favorite movie?",
    "What music do I like?",
    "What's my hobby?",
    "What sports do I play?",
    "What's my diet?",
    "Am I vegetarian?",
    "Am I vegan?",
    "What can't I eat?",
    "What foods should I avoid?",
    "What medications do I take?",
    "What's my medical condition?",
    "What health issues do I have?",
]
